//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Layer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUEGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JUEGO()
        {
            this.JUEGO_GENERO = new HashSet<JUEGO_GENERO>();
            this.PACK_DETALLE = new HashSet<PACK_DETALLE>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public int ANHO { get; set; }
        public System.DateTime FECHA_LANZAMIENTO { get; set; }
        public string ESTUDIO { get; set; }
        public decimal PRECIO { get; set; }
        public string TAGS { get; set; }
        public string DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUEGO_GENERO> JUEGO_GENERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACK_DETALLE> PACK_DETALLE { get; set; }
    }
}
