//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Layer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACK_DETALLE
    {
        public int ID { get; set; }
        public int ID_PACK { get; set; }
        public int ID_JUEGO { get; set; }
    
        public virtual JUEGO JUEGO { get; set; }
        public virtual PACK PACK { get; set; }
    }
}
