//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Layer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_VIDEOJUEGOS : DbContext
    {
        public DB_VIDEOJUEGOS()
            : base("name=DB_VIDEOJUEGOS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GENERO> GENERO { get; set; }
        public virtual DbSet<JUEGO> JUEGO { get; set; }
        public virtual DbSet<JUEGO_GENERO> JUEGO_GENERO { get; set; }
        public virtual DbSet<PACK> PACK { get; set; }
        public virtual DbSet<PACK_DETALLE> PACK_DETALLE { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
